<#
.SYNOPSIS
  Collect the large data files of all exercises into dist/, write each exercise's
  data-manifest.csv and keep .gitignore in sync. Optionally upload to the GitHub release.

.DESCRIPTION
  A file becomes a release asset if it is larger than -ThresholdMB or is a
  point cloud / archive (*.las, *.laz, *.zip). Identical files (same MD5) that are
  used by several exercises are uploaded only once.

  Run this on a machine that has the full data locally (i.e. the author's).

.EXAMPLE
  .\tools\build_release.ps1                 # build dist/ + manifests only
  .\tools\build_release.ps1 -Upload         # additionally create/upload the release via gh
#>
param(
    [int]$ThresholdMB = 10,
    [string]$Tag = 'data-v1.0',
    [switch]$Upload
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path $PSScriptRoot -Parent
$Dist = Join-Path $Root 'dist'
New-Item -ItemType Directory -Force $Dist | Out-Null

$assets  = @{}   # md5 -> asset name
$ignored = New-Object System.Collections.Generic.List[string]

Add-Type -AssemblyName System.IO.Compression.FileSystem

foreach ($ex in Get-ChildItem (Join-Path $Root 'exercises') -Directory | Sort-Object Name) {
    # Files that were extracted from a released zip are covered by the zip itself
    $fromZip = @{}
    foreach ($z in Get-ChildItem $ex.FullName -Recurse -File -Filter *.zip) {
        $zip = [IO.Compression.ZipFile]::OpenRead($z.FullName)
        foreach ($entry in $zip.Entries | Where-Object Name) {
            $full = Join-Path $z.DirectoryName $entry.FullName
            $fromZip[[IO.Path]::GetFullPath($full)] = $true
            $ignored.Add("exercises/$($ex.Name)/" + $full.Substring($ex.FullName.Length + 1).Replace('\', '/'))
        }
        $zip.Dispose()
    }

    $big = Get-ChildItem $ex.FullName -Recurse -File | Where-Object {
        ($_.Length -gt $ThresholdMB * 1MB -or $_.Extension -in '.las', '.laz', '.zip') -and
        $_.Name -notlike '.*' -and -not $fromZip.ContainsKey($_.FullName)
    } | Sort-Object FullName

    $manifest = Join-Path $ex.FullName 'data-manifest.csv'
    if (-not $big) { Remove-Item $manifest -ErrorAction SilentlyContinue; continue }

    $rows = foreach ($f in $big) {
        $rel = $f.FullName.Substring($ex.FullName.Length + 1).Replace('\', '/')
        $md5 = (Get-FileHash $f.FullName -Algorithm MD5).Hash.ToLower()

        if (-not $assets.ContainsKey($md5)) {
            $name = $f.Name -replace '[^A-Za-z0-9._-]', '_'
            if ($assets.Values -contains $name) { $name = "$($ex.Name.Substring(0,2))_$name" }
            $assets[$md5] = $name
            $dest = Join-Path $Dist $name
            if (-not (Test-Path $dest)) {
                # hard link saves disk space; fall back to a copy across volumes
                try { New-Item -ItemType HardLink -Path $dest -Target $f.FullName | Out-Null }
                catch { Copy-Item $f.FullName $dest }
            }
        }

        # Zip archives are extracted into the folder they live in
        $path = if ($f.Extension -eq '.zip') { (Split-Path $rel -Parent).Replace('\', '/') } else { $rel }
        if (-not $path) { $path = '.' }
        $ignored.Add("exercises/$($ex.Name)/$rel")
        [pscustomobject]@{ asset = $assets[$md5]; md5 = $md5; path = $path }
    }
    $rows | Export-Csv $manifest -NoTypeInformation -UseQuotes AsNeeded -Encoding utf8NoBOM
    Write-Host ("{0,-40} {1} file(s)" -f $ex.Name, @($rows).Count)
}

# Keep an explicit ignore list for the released files in .gitignore
$gi = Join-Path $Root '.gitignore'
$begin = '# >>> release assets (generated by tools/build_release.ps1) >>>'
$end   = '# <<< release assets <<<'
$text  = (Get-Content $gi -Raw) -replace "(?s)\r?\n?$([regex]::Escape($begin)).*?$([regex]::Escape($end))\r?\n?", ''
$block = @($begin) + ($ignored | Sort-Object -Unique | ForEach-Object { '/' + $_ }) + @($end)
Set-Content $gi ($text.TrimEnd() + "`n`n" + ($block -join "`n") + "`n") -NoNewline -Encoding utf8NoBOM

$total = (Get-ChildItem $Dist -File | Measure-Object Length -Sum).Sum / 1GB
Write-Host ("dist/: {0} assets, {1:N2} GB" -f (Get-ChildItem $Dist -File).Count, $total)

if ($Upload) {
    $repo = 'toihr/Advanced-Remote-Sensing-Exercises'
    gh release view $Tag --repo $repo *> $null
    if ($LASTEXITCODE -ne 0) {
        gh release create $Tag --repo $repo --title "Exercise data ($Tag)" `
            --notes "Input data for the exercises. Download with ``Rscript download_all.R`` or the scripts in ``tools/`` - see README."
    }
    foreach ($f in Get-ChildItem $Dist -File) {
        Write-Host "Uploading $($f.Name) ($([math]::Round($f.Length/1MB)) MB)"
        gh release upload $Tag $f.FullName --repo $repo --clobber
    }
}
